### ISSUE TITLE
Mostrar as ofertas do dia sem o uso do comando $pr/$promocao

### ISSUE THREAD

**Issue by Brandow** [AllanCapistrano/SteamOffersBot#30]
Não sei se é algo possível, porém acho que seria uma ideia legal, todos os dias em um determinado horario, o bot mostrar as ofertas do dia, sem precisar que um usuário digite o comando $pr/$promocao

**Comment by AllanCapistrano** [comment]
Fala @Brandow, tranquilo? Primeiramente, obrigado pela sugestão. 

Bom, esse tipo de funcionalidade é possível sim, porém tem algumas questões para a implementação:

1. Para permitir isso, o Bot tem que ter acesso a lista de canais existentes em cada servidor que ele está operando, isso requer algumas permissões adicionais. Então eu teria que atualizar as permissões do Bot (aquelas que você marca antes de adicionar o Bot ao servidor), e todos teriam que adicioná-lo novamente;
2. Além disso, teria que permitir que os usuários ativem ou não essa funcionalidade, já que podem haver pessoas que não querem que o Bot fique enviando mensagens de tempos em tempos automaticamente;
2. Também teria de permitir que os usuários escolhessem em qual canal o Bot deveria enviar a mensagem da promoção.

Dito isso, o ponto crucial mesmo é o `1.`, já que alterar as permissões atualmente é um pouco inviável.

**Mas caso tenha mais sugestões sinta-se a vontade para entrar em contato!**
